// <auto-generated />
using System;
using DatabaseConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseConnection.Migrations
{
    [DbContext(typeof(AndromedeDbContext))]
    [Migration("20211208194704_ModifyRestorerData")]
    partial class ModifyRestorerData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatabaseConnection.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RestorerId")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("RestorerId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DatabaseConnection.Restorer", b =>
                {
                    b.Property<int>("RestorerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RestaurantSiretNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("RestaurantState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Subscribed")
                        .HasColumnType("bit");

                    b.HasKey("RestorerId");

                    b.ToTable("Restorers");
                });

            modelBuilder.Entity("DatabaseConnection.RestorerClaim", b =>
                {
                    b.Property<int>("RestorerClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimGUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndOfGUID")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestorerId")
                        .HasColumnType("int");

                    b.HasKey("RestorerClaimId");

                    b.HasIndex("RestorerId");

                    b.ToTable("RestorerClaims");
                });

            modelBuilder.Entity("DatabaseConnection.Card", b =>
                {
                    b.HasOne("DatabaseConnection.Restorer", "Restorer")
                        .WithMany("Cards")
                        .HasForeignKey("RestorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restorer");
                });

            modelBuilder.Entity("DatabaseConnection.RestorerClaim", b =>
                {
                    b.HasOne("DatabaseConnection.Restorer", "Restorer")
                        .WithMany("RestorerClaims")
                        .HasForeignKey("RestorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restorer");
                });

            modelBuilder.Entity("DatabaseConnection.Restorer", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("RestorerClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
